# Generated by Django 5.0.6 on 2024-07-09 11:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator(message='Invalid email address')])),
                ('Gender', models.IntegerField(choices=[(0, 'Male'), (1, 'Female'), (2, 'Not Specified')])),
                ('Phone_number', models.CharField(max_length=13)),
                ('address', models.CharField(max_length=250)),
            ],
        ),
    ]
