# Generated by Django 5.0.6 on 2024-07-09 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='Gender',
            field=models.CharField(choices=[(0, 'Male'), (1, 'Female'), (2, 'Not Specified')], max_length=100),
        ),
    ]
