# Generated by Django 5.0.6 on 2024-07-09 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_userdata_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='Gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('NA', 'Not Specified')], max_length=100),
        ),
    ]
